// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmkfzezlrkrirftqkhvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtta2Z6ZXpscmtyaXJmdHFraHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMjEyOTksImV4cCI6MjA1NDY5NzI5OX0.F2s9w1L2Mmka6iXRKgYi4CtF2lrG7hsdgAFstE3hSP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);