// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnfsxerngbrwcpgunggm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZnN4ZXJuZ2Jyd2NwZ3VuZ2dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDMzODksImV4cCI6MjA1NTQ3OTM4OX0.fJRoe0h3N0OX5I3VJS2FxQenVp3dLY1ISG2100NLuXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);